### ISSUE TITLE
如何在每个request中打印username？

### ISSUE THREAD

**Issue by shuaiyy** [things-go/go-socks5#11]
出于安全审计需要，如何在用户每次请求时，打印 时间、username，源ip和目标ip？

**Comment by thinkgos** [comment]
简单点就在 ruleset 做, 那个可以自己写. 那个有request 的上下文

**Comment by shuaiyy** [comment]
> 简单点就在 ruleset 做, 那个可以自己写. 那个有request 的上下文
谢谢大佬，通过ruleset可以实现
