### ISSUE TITLE
[FR] Dial callback with request information

### ISSUE THREAD

**Issue by kotori2** [things-go/go-socks5#44]
I want to implement: Use different IP based on different username provided. 
To achieve that, I need to access the `AuthContext` in `socks5.Request`. But currently dial callback doesn't have such parameter. 
My current workaround is to use `socks5.WithConnectHandle` with the entire `func (sf *Server) handleConnect(ctx context.Context, writer io.Writer, request *Request) error` function body copied to my own code, since I can't override or call it directly.

**Comment by thinkgos** [comment]
PR welcome
