### ISSUE TITLE
Use go-socks5 for someone unfamiliar with go

### ISSUE THREAD

**Issue by ni-todo-spot** [things-go/go-socks5#50]
Hey All!,

I've encountered this project via https://github.com/metalbear-co/mirrord/issues/1944#issuecomment-1772096933.

I've installed go and tried to install this package, but got an error:

```
%     go get install github.com/things-go/go-socks5                          
go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
```

When trying suggested go install, I get:
```
%     go install github.com/things-go/go-socks5@latest
package github.com/things-go/go-socks5 is not a main package
```

Can I get help installing this package please?
Using MacOS & go version go1.18.10 darwin/amd64

Thanks In advance!

**Comment by thinkgos** [comment]
this is a package, not a binary, not main package. see [example](https://github.com/things-go/go-socks5/tree/master/_example). if you use with module. must be run `go mod init` in your project.  see [go module](https://go.dev/doc/tutorial/create-module)
