### ISSUE TITLE
UDP proxy close bind socket when read from remote failed, but don't close proxy socket!!!

### ISSUE THREAD

**Issue by wwcd** [things-go/go-socks5#55]
![image](https://github.com/things-go/go-socks5/assets/2525504/67930d3e-469e-4029-84cc-cece8b690bcf)

udp proxy close bind socket when read from remote failed, but don't close proxy socket! scene as above.

https://github.com/things-go/go-socks5/blob/44f644e8fbb80bc3417612eaa6144b5b8703114b/handle.go#L249-L256

**Comment by thinkgos** [comment]
welcome pr

**Comment by wwcd** [comment]
I carefully read the implementation of v0.0.5 and found that this problem has been solved, but the implementation of v0.0.3 is problematic.
